### PR TITLE
01.00.27

### PR DESCRIPTION
**Pull request by doutriaux1**
@taylor13 @durack1 please review changes.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@taylor13 there are some really long comments in there

**Comment by doutriaux1** [comment]
@taylor13 while replacing `"value": "m"` with `"value": "84000"` I noticed that `p840` as bound_values set to: `"100000.0 68000.0",` while `p850` as not bounds set. Is this something we need to worry about?

**Comment by taylor13** [comment]
p840 is the center of a cloud layer extending from 1000 to 680, but p850 is the level at 850 (where the values are defined).  So I think it's o.k.

**Comment by taylor13** [comment]
@doutriaux1 Can we close this yet?

**Comment by doutriaux1** [comment]
it's merged, hence closed.

**Pull request merged**
