### PR TITLE
Fixes cell_methods for masscello, thkcello, volcello

### PR DESCRIPTION
**Pull request by adcroft**
- Variable `volcello` should have cell method "area: sum volume: sum". The current value of "area: mean" is simply wrong for an extensive quantity.
- Variable `volcello` should not have a self-referencing cell measure (in the same way areacello does not).
  - It is not clear whether `volcello` should have any cell measures but if the methods are corrected to "sum" it will do no harm.
- Variable `masscello` is vertically integrated (over 3d cells) and therefore should include "olevel: sum".
- Variable `thkcello` is vertically integrated (over levels) and therefore should include "olevel: sum".

### CODE REVIEW

**Comment by taylor13** [comment]
I don't understand whether this pull request should be merged or not.  I think not.  I think the problem was in the data request.   Can we close this?  (Looks like @durack1  already closed it once.)  Why was it re-opened?  @dnadeau4 is listed as a reviewer.  Does he have to do something?

**Comment by durack1** [comment]
@taylor13 the issue that was closed (referenced above) was cmip6dr/CMIP6_DataRequest_VariableDefinitions#361 which was the upstream fix that was required - if we check in our downstream cmip6-cmor-tables, then I assume that the fix applied by Martin will propagate without any requirement from us - I haven't checked though, if it's done, then close away

**Comment by mauzey1** [comment]
@taylor13 @durack1 This pull request has been sitting here for several months.  Have changes from the recent data requests made these changes unnecessary?

**Comment by taylor13** [comment]
I have raised an issue at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/394  .  If Martin fixes any problems there, they will propagate to us without any changes to our codes (with the next data request release).  I'll close this now.

**Pull request closed without merging**
