### PR TITLE
Update to 01.00.28b1

### PR DESCRIPTION
**Pull request by mauzey1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
Thanks @mauzey1 . @taylor13 @durack1 please review this for Martin. Test are failing but I suspect it is because version cannot have `b1` in it. This will be resolved when Martin updates to `28`

**Comment by durack1** [comment]
@mauzey1 @doutriaux1 this looks fine to me, but it would be great if the tests were able to deal with the `*b1` tag and not error, there are some variables that are removed and added in this change, so not sure these will cause problems elsewhere

**Comment by doutriaux1** [comment]
@durack1 it's a prepare requirement, prepare actually checks that the version has only numbers.

**Comment by mauzey1** [comment]
I tried testing the changes that were copied to CMOR's tables and got errors when running CMIP6 CV Python tests for the following test:

         Test/test_python_CMIP6_CV_parenttimeunits.py
         Test/test_python_CMIP6_CV_hierarchicalattr.py
         Test/test_python_CMIP6_CV_badgridresolution.py
         Test/test_python_CMIP6_CV_badinstitutionIDNotSet.py
         Test/test_python_CMIP6_CV_furtherinfourl.py
         Test/test_python_CMIP6_CV_trackingprefix.py
         Test/test_python_CMIP6_CV_externalvariables.py
         Test/test_python_CMIP6_CV_badsource.py
         Test/test_python_CMIP6_CV_trackingNoprefix.py
         Test/test_python_CMIP6_CV_HISTORY.py
         Test/test_python_CMIP6_CV_forcenoparent.py
         Test/test_python_CMIP6_CV_fxtable.py

The test that is failing in the circleci is Test/test_python_CMIP6_CV_terminate_signal.py, which had no errors when I ran it on my workstation.  The other tests in circleci passed including the ones I listed above.  Is there another step I need to do to get the changes working in CMOR?

**Comment by doutriaux1** [comment]
@taylor13 @durack1 @mauzey1 updated the tables to have correct drs version
for future ref the code was:
```python
from __future__ import print_function
import glob

tables = glob.glob("CMIP6*json")

for table in tables:
    print("Cleaning:", table)
    with open(table) as f:
        content = f.read()
        content = content.replace("01.00.28b1","01.00.28")
    with open(table, "w") as f:
        f.write(content)

print("Done")
```

**Comment by durack1** [comment]
Thanks @doutriaux1

**Comment by taylor13** [comment]
@doutriaux1 Two questions:
1) Do the CMOR tests all pass now for the new release (28b1)?
2) How can I review the new tables and see what has changed relative to release 27?

**Comment by doutriaux1** [comment]
@taylor13 all the checks are "Green" so the tests pass, to see the change at the top of this page click on `Files changed` (I know it's not obvious 😆 )

**Comment by durack1** [comment]
@mauzey1 @doutriaux1 the [01.00.28 full release](http://clipc-services.ceda.ac.uk/dreq/index.html) is out (was released on the 15th October 2018). Can we update this PR to reflect the full release? And then merge soon therafter?

**Comment by durack1** [comment]
@mauzey1 is this the one to review now? Also the CMIP6_CVs repo is now up to 6.2.14.2, so would be great to also update that alongside (or within) this PR, then this repo will be 100% up to date

**Comment by mauzey1** [comment]
@durack1 Yes, I have updated the branch for this pull request for review.

A cronjob will update the master CMIP6_CV at midnight.

**Comment by durack1** [comment]
@mauzey1 great, that cronjob has updated us to 6.2.14.2 so it's just a matter of reviewing the table changes in this PR and then we can tag a new up-to-date release.

@taylor13 and I will get to this in the next couple of days

**Comment by mauzey1** [comment]
@durack1 Yes, this uses the latest version of 01.00.28.

**Pull request merged**
