### PR TITLE
Add license_info to models in CMIP6_CV.json

### PR DESCRIPTION
**Pull request by mauzey1**
@durack1 These changes don't seem to affect the current CMOR usage of the `license` attribute so I think we can merge these changes now.

### CODE REVIEW

**Comment by durack1** [comment]
@mauzey1 it would be great to catch the `license` template at https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_input_example.json#L40 and update this to reflect the final string after the "code" in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1050#issuecomment-1136439821

**Comment by mauzey1** [comment]
@durack1 Okay.  So we want to have the 'license' template as described in https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1050#issuecomment-1136439821 to be in CMIP6_CV.json, and have CMOR fill in the template to populate the `license` attribute?

**Comment by durack1** [comment]
@mauzey1 I think that would be ideal, so we require inputs from the CMOR users, which are included in the input.json

**Comment by mauzey1** [comment]
@durack1 So license_id and license_url come from the user?  But those don't get stored in the NetCDF file as `license_id` and `license_ur`, right?

**Comment by durack1** [comment]
If we have a user provide two pieces of info `institution_id = "AWI"` we can look up the text from `CMIP6_institution_id.json` and `license_id = "CC BY 4.0"` from the `CMIP6_license.json` which are all available to CMOR, right? (or do we need to add these to the CMIP6_CV.json)

**Comment by mauzey1** [comment]
The current `license` template is in the script that builds CMIP6_CV.json from the WCRP files.
https://github.com/PCMDI/cmip6-cmor-tables/blob/4cb585806117cd99bd31905c72b76d2f03b14ab7/scripts/createCMIP6CV.py#L86

We should replace that with the `license` template in the JSON file.
```
    "license":{
        "license":"CMIP6 model data produced by <Your Institution; see CMIP6_institution_id.json> is licensed under a <Creative Commons; select and insert a license_id; see below> License (<insert the matching license_url; see below>). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file)[ and at <some URL maintained by modeling group>]. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.",
        "license_options":{
            "CC BY 4.0":{
                "license_id":"Creative Commons Attribution 4.0 International",
                "license_url":"https://creativecommons.org/licenses/by/4.0/"
            },
            "CC BY-NC-SA 4.0":{
                "license_id":"Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International",
                "license_url":"https://creativecommons.org/licenses/by-nc-sa/4.0/"
            },
            "CC BY-SA 4.0":{
                "license_id":"Creative Commons Attribution-ShareAlike 4.0 International",
                "license_url":"https://creativecommons.org/licenses/by-sa/4.0/"
            },
            "CC0 1.0":{
                "license_id":"Creative Commons CC0 1.0 Universal Public Domain Dedication",
                "license_url":"https://creativecommons.org/publicdomain/zero/1.0/"
            }
        }
    }
```

This will require a change to CMOR in order to work properly.  Previous version of CMOR will not work after changing the license template.

**Comment by durack1** [comment]
@mauzey1 thanks for the update. I assumed that we'd need to update CMOR to deal with the new format. I suggest we wrap this into the 3.7.0 changes planned, alongside the tweaks in https://github.com/PCMDI/cmor/issues/628

@taylor13 @matthew-mizielinski pinging you guys here

**Comment by mauzey1** [comment]
@durack1 Yes, I have already made an issue for it here: https://github.com/PCMDI/cmor/issues/656

**Comment by mauzey1** [comment]
@durack1 

After further investigation, changing the current license template should not affect the current version of CMOR.  I've discovered that CMOR only acquires the license from the user input.  Not adding a `license` attribute to your user input will cause an error in CMOR.  CMOR currently ignores the license template from the CV file; deleting the license template from CMIP6_CV.json did not affect CMOR's operation.

This means we could proceed with adding a new license template to the CV file little issue.  We can then add the feature to read the template in CMOR later.

**Comment by mauzey1** [comment]
@durack1 Should we change the template text for the institution name to something that is MIP-neutral for CMOR?
From this...
```
<Your Institution; see CMIP6_institution_id.json>
```
to this...
```
<Your institution's name; see the institution_id section>
```
We can change the text from within the script that builds CMIP6_CV.json from the WCRP-CMIP files.

**Comment by mauzey1** [comment]
The reason why the tests are not passing here is because the user input for them is using an outdated version of the license string.  The changes from https://github.com/PCMDI/cmor/pull/657 will update those license strings.  The tests in that PR are using the CMIP6_CV.json from this branch's PR.

@durack1 As soon as https://github.com/PCMDI/cmor/pull/657 is merged, I will update this PR.

**Comment by mauzey1** [comment]
The reason why the tests are not passing here is because the user input for them is using an outdated version of the license string.  The changes from https://github.com/PCMDI/cmor/pull/657 will update those license strings.  The tests in that PR are using the CMIP6_CV.json from this branch's PR.

@durack1 As soon as https://github.com/PCMDI/cmor/pull/657 is merged, I will update this PR.

**Comment by durack1** [comment]
@mauzey1 perfect, thanks

**Pull request closed without merging**
