### PR TITLE
Update CMIP6_CV.json

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Adds PAMIP to the E3SM-1-0 activity participation.

### CODE REVIEW

**Comment by mauzey1** [comment]
@durack1 Shouldn't changes to CMIP6_CV.json come from upstream from https://github.com/WCRP-CMIP/CMIP6_CVs?

The changes in this pull request would be clobbered by the next time changes are made in the WCRP-CMIP repo.

**Comment by sterlingbaldwin** [comment]
Do you know which of the json files in that repo I should update to get this change in?

**Comment by mauzey1** [comment]
@sterlingbaldwin The file that should be updated is [CMIP6_source_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/a87149fb137835b92351a300e2358027fab8a0b3/CMIP6_source_id.json#L2194-L2199).

**Comment by durack1** [comment]
@sterlingbaldwin yep, those changes are required upstream in https://github.com/WCRP-CMIP/CMIP6_CVs, please open a new issue (or reopen https://github.com/WCRP-CMIP/CMIP6_CVs/issues/534) and note that PAMIP needs to be added.

There is a cron job that pulls these registered changes across nightly

**Comment by sterlingbaldwin** [comment]
Does this work: https://github.com/WCRP-CMIP/CMIP6_CVs/pull/1029 ?

**Pull request closed without merging**
