### PR TITLE
Use nightly cmor for testing

### PR DESCRIPTION
**Pull request by mauzey1**

### CODE REVIEW

**Comment by mauzey1** [comment]
@doutriaux1 I tried applying the same change you made in the 01.00.28b1 branch for .circleci/config.yml but the CI checks still failed.  The errors are different from before but are still related to libhdf5.

ERROR: Failure: ImportError (dlopen(/Users/distiller/project/workspace/test_macos_cmor/miniconda/envs/py2/lib/python2.7/site-packages/cmor/_cmor.so, 2): Library not loaded: @rpath/libhdf5.101.dylib
  Referenced from: /Users/distiller/project/workspace/test_macos_cmor/miniconda/envs/py2/lib/python2.7/site-packages/cmor/_cmor.so
  Reason: image not found)

**Comment by doutriaux1** [comment]
@mauzey1 I will take a look shortly. Thanks for getting it started.

**Comment by doutriaux1** [comment]
@mauzey1 on my mac, it complains about libstd++ ...

**Comment by doutriaux1** [comment]
@mauzey1 looks like cmor was built against:
```
    hdf5:            1.10.2-hc401514_2                   conda-forge

```

Let's add the following option to cmor config_build.yaml:

```
pin_run_as_build:
   hdf5: x.x
```

**Comment by doutriaux1** [comment]
@mauzey1 for now, just edit the config.yml and force to use the correct hdf5 1.10.2

**Comment by doutriaux1** [comment]
@mauzey1 also lobcdms seem to ask for netcdf> 4.5 and cmor netcdf 4.4

**Pull request merged**
