### PR TITLE
removed old mip tables.

### PR DESCRIPTION
**Pull request by jkettleb**
Hello Denis,

I think there are a couple of MIP tables left as debris from a previous version.  Could/should they be deleted?

Thanks,
Jamie

### CODE REVIEW

**Comment by dnadeau4** [comment]
I need the `excerpt` for my [documentation](http://cmor.llnl.gov/mydoc_cmip6_table_excerpt/).

When I created the cmip6_cfSites.json table from @martinjuckes ```dreq.xml``` database,  I got some [variables](https://github.com/PCMDI/cmip6-cmor-tables/blob/f58d55a30422f8eef75306fd468e0a8a3d35b31c/Tables/CMIP6_cfSites.json#L1809-L1825) that were selected.   Is cmip6_cfSites still valid @taylor13

**Comment by jkettleb** [comment]
Thanks for picking this up @dnadeau4.  I think there has been a change of case in cmip6_cfSites - the new version appears to be cmip6_cfsites (I don't think cmip6_cfSites was generated from beta.30 of the data request)

Good idea to have excerpt in the documentation.  Is it a little clearer for users of the tables though if its held somewhere else rather than with all these other tables?

Thanks,
Jamie

**Comment by dnadeau4** [comment]
@jkettleb I'll put the "excerpt" in my  the github cmor documentation repository(https://github.com/PCMDI/cmor3_documentation). 

You are right that case sensitive is a breaks the MAC OSX version of CMOR.  OSX is a not a case sensitve operating system.   I will merge your pull request.  Thanks!

**Comment by jkettleb** [comment]
Thanks @dnadeau4.

**Pull request merged**
